### PR TITLE
Fixes misspelling of CredentialBootstrap in readMe file line number 147

### PR DESCRIPTION
**Pull request by ritesh-spoton**
Fixes misspelling of CredentialBootstrap in readMe file line number 147.

CredentialBoostrap --> CredentialBootstrap

### CODE REVIEW

**Comment by JayNewstrom** [comment]
Thanks!

**Comment by JayNewstrom** [comment]
Looks like the build is failing because it’s coming from a fork. I’ll try to improve this in the future. But I’ll just bring this one in manually for you. I’m on PTO this week, but I’ll take care of this first thing next week at the latest. Thanks again for the contribution!

**Comment by ritesh-spoton** [comment]
Thanks Jay

Happy to contribute.

**Comment by JayNewstrom** [comment]
Thanks again! Sorry for the delay!

**Pull request merged**
